export interface Project {
project_id:number   ;
agency:string   ;
fiscal_year:string   ;
budget: string ;
product: string ;
sub_product: string ;
project_name: string ;
project_character: string ;
development_plan: string ;
strategic: string ;
goal: string ;
strategy: string ; 
measure: string ;
plans: string ;
reason: string ;
objective: string ;
target_group_student:number  ;
target_group_personnel:number  ;
target_group_outsider:number  ;
user_id:number  ;
place:string  ;
startdate:string  ;
enddate:string  ;
implementation:string  ;
indicators:string  ;
cost:number  ;
expect_result:string  ;
project_evaluation: string ;
follow_up:string  ;
project_proponent:number  ;
project_approver:number  ;
project_status:string  ;
created_date:string  ;
created_by:string  ;
updated_date:string  ;
updated_by:string  ;
period:string  ;
first_name:string  ;
last_name:string  ;
}